### ISSUE TITLE
Pip package

### ISSUE THREAD

**Issue by mehulfollytobevice** [cibinjoseph/json2txttree#1]
Hi, 
I found the code in this repository very useful. I would really appreciate if you can release a python package based on this repository. That way, we can use the code using pip install.

**Comment by cibinjoseph** [comment]
Sure. I'll try to make it a package this week. Only reason I haven't already is because I didn't find anyone using it a lot!

**Comment by cibinjoseph** [comment]
This library has been converted to a pip package with the name `json2txttree` at [https://pypi.org/project/json2txttree/](https://pypi.org/project/json2txttree/).

**Comment by mehulfollytobevice** [comment]
Thanks, I will definitely try it out.
